from typing import TypedDict
from pydantic import BaseModel, Field


class GameMasterState(BaseModel):
    """
        The shared state dictionary for the AI system.
        Strictly validated by Pydantic at every node transition.
    """
    # --- Input Variables (Populated at START) ---
    user_query: str = Field(
        ..., 
        description="The initial question asked by the player."
    )
    chat_summary: str = Field(
        default="", 
        description="Condensed summary of the long-term conversational context."
    )
    recent_history: list = Field(
        default_factory=list, 
        description="The sliding window of the most recent chat turns."
    )
    
    
    # --- Phase 1: Routing & Expansion ---
    guessed_systems: list[str] = Field(
        default_factory=list, 
        description="The game systems identified by the Phase 1 Router."
    )
    clean_query: str = Field(
        default="", 
        description="The user's query stripped of conversational filler."
    )
    expanded_keywords: list[str] = Field(
        default_factory=list, 
        description="Domain-specific jargon generated by the Keyword Expander."
    )
    
    
    # --- Phase 1: Reflection Loop Data ---
    phase_1_passed: bool = Field(
        default=False, 
        description="Boolean flag set by the Critic: True if routing is valid, False if it needs retry."
    )
    phase_1_feedback: str = Field(
        default="", 
        description="Critique from the Router Auditor on why a routing attempt failed."
    )
    phase_1_retries: int = Field(
        default=0, 
        ge=0, # Validation: Must be Greater than or Equal to 0
        description="Tracks the number of Phase 1 reflection loops."
    )
    
    
    # --- Phase 2: Retrieval & Generation ---
    retrieved_context: str = Field(
        default="", 
        description="The formatted string of rulebook chunks pulled from the database."
    )
    draft_response: str = Field(
        default="", 
        description="The current generated answer draft."
    )
    
    
    # --- Phase 2: Reflection Loop Data ---
    phase_2_passed: bool = Field(
        default=False, 
        description="Boolean flag set by the Critic: True if hallucination-free, False if it needs retry."
    )
    phase_2_feedback: str = Field(
        default="", 
        description="Critique from the Hallucination Auditor on factual inaccuracies."
    )
    phase_2_retries: int = Field(
        default=0, 
        ge=0, # Validation: Must be Greater than or Equal to 0
        description="Tracks the number of Phase 2 reflection loops."
    )