from pydantic import BaseModel, Field
from langchain_core.prompts import ChatPromptTemplate
from langchain_google_genai import ChatGoogleGenerativeAI

import json
import time
# Assuming 'app' is your compiled LangGraph workflow from earlier
# Assuming 'golden_dataset' is the list of dictionaries from the previous step

# ==========================================
# 1. Structured Output Schemas
# ==========================================
class EvaluationScore(BaseModel):
    score: int = Field(
        description="Strictly 1 if the criteria is met, or 0 if it fails."
    )
    reasoning: str = Field(
        description="A 1-2 sentence explanation of why the score was given."
    )

# ==========================================
# 2. Context Relevance Prompt (Tests Retrieval)
# ==========================================
# Intuition: We compare the User Question against the Context your Database pulled. 
# We DO NOT look at the AI's final answer here.
CONTEXT_RELEVANCE_PROMPT = ChatPromptTemplate.from_messages([
    ("system", 
     "You are an expert evaluator grading a Retrieval-Augmented Generation (RAG) system.\n"
     "Your task is to evaluate 'Context Relevance'.\n"
     "Look at the USER QUESTION and the RETRIEVED CONTEXT.\n"
     "If the RETRIEVED CONTEXT contains enough information to accurately answer the USER QUESTION, score it 1.\n"
     "If the RETRIEVED CONTEXT is irrelevant, completely off-topic, or missing critical rules needed to answer the question, score it 0."
    ),
    ("human", 
     "USER QUESTION: {question}\n\n"
     "RETRIEVED CONTEXT: {retrieved_context}"
    )
])

# ==========================================
# 3. Faithfulness Prompt (Tests Generation)
# ==========================================
# Intuition: We compare the Final Answer against the Retrieved Context.
# We DO NOT care about the original question here. We only care if the LLM hallucinated.
FAITHFULNESS_PROMPT = ChatPromptTemplate.from_messages([
    ("system", 
     "You are an expert evaluator grading a Retrieval-Augmented Generation (RAG) system.\n"
     "Your task is to evaluate 'Faithfulness' (Hallucination detection).\n"
     "Look at the RETRIEVED CONTEXT and the AI GENERATED ANSWER.\n"
     "If every claim, rule, and number in the AI GENERATED ANSWER is explicitly supported by the RETRIEVED CONTEXT, score it 1.\n"
     "If the AI GENERATED ANSWER invents rules, brings in outside knowledge, or contradicts the RETRIEVED CONTEXT, score it 0."
    ),
    ("human", 
     "RETRIEVED CONTEXT: {retrieved_context}\n\n"
     "AI GENERATED ANSWER: {draft_response}"
    )
])

# ==========================================
# 4. Bind the Judge Chains
# ==========================================
# We use the smarter critic model to ensure the grading is highly accurate
llm_critic = ChatGoogleGenerativeAI(
    # model="gemma-4-26b-it",  # The standard naming convention for Gemma instruct models
    model="gemma4:26b",
    temperature=0.0,         # Kept at 0.0 for deterministic evaluation
    max_retries=2
)
judge_llm = llm_critic.with_structured_output(EvaluationScore)

context_relevance_chain = CONTEXT_RELEVANCE_PROMPT | judge_llm
faithfulness_chain = FAITHFULNESS_PROMPT | judge_llm


# ==========================================
# 5. The Evaluation Harness (Execution Loop)
# ==========================================
def run_evaluation_suite(dataset: list, graph_app) -> list:
    results_log = []
    
    print(f"Starting Evaluation Suite for {len(dataset)} cases...\n")
    
    for index, test_case in enumerate(dataset):
        print(f"--- Running Test Case {index + 1}: {test_case['query_type']} ---")
        
        # 1. Setup a fresh initial state for the graph
        # It is critical to reset all keys so previous test states do not leak
        initial_state = {
            "user_query": test_case["question"],
            "recent_history": [],
            "chat_summary": "",
            "guessed_systems": [],
            "clean_query": "",
            "phase_1_retries": 0,
            "phase_2_retries": 0,
            "phase_1_feedback": "",
            "phase_2_feedback": "",
            "phase_1_passed": False,
            "phase_2_passed": False,
            "retrieved_context": "",
            "draft_response": ""
        }
        
        # 2. Execute the LangGraph pipeline
        print("  -> Executing LangGraph Pipeline...")
        final_state = None
        
        # stream_mode="values" yields the full state dictionary at each step.
        # We loop through until the graph finishes to capture the absolute final state.
        for state_snapshot in graph_app.stream(initial_state, stream_mode="values"):
            final_state = state_snapshot
            
        # Extract the variables generated by your pipeline
        actual_context = final_state.get("retrieved_context", "")
        actual_answer = final_state.get("draft_response", "")
        
        # 3. Grade Context Relevance (Did we retrieve the right rules?)
        print("  -> Grading Context Relevance...")
        try:
            relevance_eval = context_relevance_chain.invoke({
                "question": test_case["question"],
                "retrieved_context": actual_context
            })
        except Exception as e:
            # Fallback if the Judge LLM fails to format its Pydantic output
            relevance_eval = EvaluationScore(score=0, reasoning=f"Judge Failed: {e}")

        # 4. Grade Faithfulness (Did the GM hallucinate?)
        print("  -> Grading Faithfulness...")
        try:
            faithfulness_eval = faithfulness_chain.invoke({
                "retrieved_context": actual_context,
                "draft_response": actual_answer
            })
        except Exception as e:
            faithfulness_eval = EvaluationScore(score=0, reasoning=f"Judge Failed: {e}")
            
        # 5. Store the Results
        result_record = {
            "test_case": test_case["question"],
            "expected_context": test_case["ground_truth_context"],
            "ideal_answer": test_case["ideal_answer"],
            "actual_context_preview": actual_context[:200] + "..." if actual_context else "None",
            "actual_answer": actual_answer,
            "relevance_score": relevance_eval.score,
            "relevance_reason": relevance_eval.reasoning,
            "faithfulness_score": faithfulness_eval.score,
            "faithfulness_reason": faithfulness_eval.reasoning
        }
        
        results_log.append(result_record)
        print(f"  -> Case {index + 1} Done! [Relevance: {relevance_eval.score}, Faithfulness: {faithfulness_eval.score}]\n")
        
        # Optional: Sleep briefly to avoid hitting LLM API rate limits if using a cloud judge
        time.sleep(2)
        
    return results_log