import os
from pathlib import Path
from dataclasses import dataclass


@dataclass
class PersistentVars:
    """Class stores important persistent variables."""
    # Embedding model
    EMBBEDDING_MODEL = "BAAI/bge-small-en-v1.5"
    
    
    ROOT_DIR = Path(os.getcwd()).parents[0]
    
    DATA_FOLDER = ROOT_DIR / "data"
    
    # Stores path to vector db
    DB_PATH: Path = ROOT_DIR / "vectorDB" / "chromaDB"
    
    # Stores Path to the systems.json
    SYSTEMS_MANIFEST: Path = ROOT_DIR / "vectorDB" / "systems.json"
    
    # Vector Collection Name
    COLLECTION = "TTRPG_Data"
    
    # Metadata Tags
    METADATA = {
        "systems": "system"
    }
    
    # Custom Log txt File
    LOG_FILE = ROOT_DIR / "graph_log.txt"
    
    # Path to custom log file for the data ingestion pipeline
    DATA_LOG_FILES = ROOT_DIR / "data_log.txt"

   
@dataclass
class GraphAgentPrompts:
    """Holds system prompts for the LLMs"""
    # Hyper-Specific Router System Prompt   
    ROUTER_SYSTEM_PROMPT: str = (
        "You are a strict, non-conversational Intent Classification & Query Optimization Engine for Tabletop RPGs.\n"
        "Your ONLY responsibility is to analyze the user's input alongside conversational history and produce a structured JSON object.\n\n"
        "CONTEXTUAL ROUTING & CLASSIFICATION RULES:\n"
        "1. Current Query Priority: If the user EXPLICITLY mentions one of the target systems (or a common abbreviation like 'dnd' or 'pf2e'), add the official name to the `system` list.\n"
        "2. System Comparisons: If the user asks to compare mechanics across multiple games, include ALL relevant system names in the `system` list.\n"
        "3. Implicit Reference (Memory): If the current query lacks an explicit system, analyze the 'Recent History' and 'Previous Chat Summary'. If a game is clearly the active subject, map to that system.\n"
        "4. Anti-Hallucination (Strict Fallback): If NO system is mentioned and history does not establish one, YOU ARE STRICTLY FORBIDDEN FROM GUESSING. Set `system` to ['multiple'].\n"
        "5. Query Optimization: Strip all conversational noise, game system names, AND abbreviations from the `clean_query`. Output ONLY dense, high-signal search mechanics.\n"
        "6. Boundary Enforcement: DO NOT ANSWER THE USER'S QUESTION UNDER ANY CIRCUMSTANCES.\n\n"
        "TARGET SYSTEMS (Map all user abbreviations to these exact strings):\n"
        "{active_systems}\n\n"
        "PREVIOUS CHAT SUMMARY:\n"
        "{chat_summary}\n\n"
        "Output ONLY valid JSON matching the schema."
    )
    
    ROUTER_USER_PROMPT: str = (
        "PREVIOUS RETRY FEEDBACK (If any):\n{feedback}\n\n"
        "RECENT CHAT HISTORY:\n{recent_history}\n\n"
        "CURRENT USER QUESTION:\n{question}"
    )


    # Router Critic Prompts
    ROUTER_GRADER_SYSTEM: str = (
        "You are an expert QA auditor for an AI Query Routing Engine.\n"
        "Your task is to review a proposed 'QueryIntent' classification generated by a router.\n\n"
        "EVALUATION CRITERIA:\n"
        "1. System Extraction: Did the router include ALL explicit systems mentioned in the current question? \n" #(Note: The router must use the exact strings from the Active Systems List, even if they contain typos. Accept them as correct.)\n"
        "2. Contextual Systems: Did the router correctly capture active systems from the Chat Summary or Recent History when implicit references are made?\n" # (If history is 'None', ignore this).\n"
        "3. Cross-System Comparison: If the user introduced a new game system while another was active in history/summary, did the router include BOTH systems?\n"
        # "4. Clean Query Quality: Is 'clean_query' completely stripped of conversational filler, system names, AND acronyms (like 'dnd'), while preserving core mechanical terms?\n\n"
        "4. Clean Query Quality: Is 'clean_query' completely stripped of conversational filler while preserving core mechanical terms?\n\n"
        # "CRITICAL INSTRUCTION FOR PASSING:\n"
        # "If the Proposed Intent successfully meets ALL the criteria above, you MUST set `phase_1_passed` to true and leave `phase_1_feedback` empty. Only output false if a specific, undeniable error is found.\n\n"
        "Output ONLY valid JSON matching the schema."
    )

    ROUTER_GRADER_USER: str = (
        "INPUT DATA:\n"
        "- User Question: {question}\n"
        "- Chat Summary: {chat_summary}\n"
        "- Recent History: {recent_history}\n"
        "- Active Systems List: {active_systems}\n\n"
        "PROPOSED INTENT:\n"
        "- Selected Systems: {selected_systems}\n"
        "- Clean Query: {clean_query}\n\n"
    )

    
    # Summary Generation Chain (for ambiguous queries)
    SUMMARIZER_SYSTEM_PROMPT: str = (
        "You are an expert TTRPG Game Master assistant.\n"
        "The user asked a mechanical question, but based on the current query and conversational history, it is ambiguous which game system they are playing.\n"
        "Below is the previous chat context, recent chat history and the top relevant rule excerpts retrieved directly from our database across multiple systems.\n\n"
        "PREVIOUS CHAT SUMMARY:\n"
        "{chat_summary}\n\n"
        "RECENT CHAT HISTORY:\n"
        "{recent_history}\n\n"
        "TASK & STRICT RULES:\n"
        "1. Summarize in 1-2 concise sentences how this mechanic operates based ONLY on the 'Retrieved Rule Excerpts'.\n"
        "2. Explicitly attribute mechanics to their respective systems (e.g., 'In D&D 5e... whereas in Pathfinder...').\n"
        "3. Use the chat summary for conversational context, but do not guess the system if it remains ambiguous.\n"
        "4. Conclude with a single direct question asking the user to clarify which system they are using.\n\n"
        "RETRIEVED RULE EXCERPTS:\n"
        "{retrieved_context}"
    )
    
    SUMMARIZER_USER_PROMPT: str = (
        "INPUT DATA:\n"
        "- User Question: {question}\n"
        "- Active Systems List: {active_systems}\n\n"
    )
    
    
    # Summary Generation Model Prompt
    MEMORY_SUMMARY_PROMPT: str = (
        "You are a memory manager for a Tabletop RPG Game Master AI.\n"
        "Your task is to progressively update a running summary of the conversation.\n"
        "Integrate the 'New Lines' into the 'Current Summary'.\n\n"
        "RULES:\n"
        "1. Keep it dense and succinct. Focus on established context, game systems, and specific rules discussed.\n"
        "2. Discard conversational filler (e.g., 'Hello', 'Thanks').\n"
        "3. If the 'Current Summary' is empty, simply summarize the 'New Lines'.\n\n"
        "CURRENT SUMMARY:\n{chat_summary}\n\n"
        "NEW LINES TO SUMMARIZE:\n{new_lines}"
    )

    
    # Game Master Prompt
    GAME_MASTER_SYSTEM_PROMPT: str = (
        "You are an expert, friendly Tabletop RPG Game Master.\n"
        "Your job is to answer the user's rules question using ONLY the provided official rulebook excerpts.\n\n"
        "Use the summary of the chat provided to extend the context of the user query as required.\n"
        "CHAT SUMMARY:\n"
        "{chat_summary}\n\n"
        "RECENT CHAT\n"
        "{recent_history}\n\n"
        "STRICT RULES:\n"
        "1. Base your answer entirely on the 'Retrieved Context' below. Do not use outside knowledge.\n"
        "2. If the context does not contain the answer, politely state that you do not have that specific rule in your current database.\n"
        "3. Format your answer clearly using Markdown (bullet points, bold text for mechanics) for readability.\n"
        "4. Keep the tone helpful, concise, and focused on resolving the mechanical question.\n\n"
        "RETRIEVED CONTEXT:\n"
        "{retrieved_context}"
    )
    
    GAME_MASTER_USER_PROMPT: str = (
        "\n{question}\n"
    )
    

    # Hallucination grader to check the GM LLM's response
    GM_GRADER_SYSTEM: str = (
        "You are a strict rules auditor for a Tabletop RPG system.\n"
        "You will be provided with a set of official rule excerpts (FACTS) and an AI-generated answer (GENERATION).\n"
        "Your ONLY responsibility is to verify that the GENERATION does not invent, hallucinate, or assume any mechanics not explicitly stated in the FACTS.\n\n"
        "GRADING RUBRIC:\n"
        "- If the GENERATION contains a single rule, number, or claim not found in the FACTS, output 'no'.\n"
        "- If the entire GENERATION is strictly supported by the FACTS, output 'yes'.\n\n"
        "Output ONLY valid JSON matching the schema."
    )
    
    GM_GRADER_USER: str = (
        "FACTS:\n"
        "{retrieved_context}\n\n"
        "GENERATION:\n"
        "{draft_response}\n\n"
    )
    
        
    # SystemCA prompt to return a game system independently
    SYSTEMCA_SYSTEM_PROMPT: str = (
        "You are a strict, non-conversational System Classification Engine for Tabletop RPGs.\n"
        "Your ONLY responsibility is to analyze the user's input alongside conversational history and produce a structured JSON object.\n\n"
        "CONTEXTUAL ROUTING & CLASSIFICATION RULES:\n"
        "1. Current Query Priority: If the user EXPLICITLY mentions one of the target systems (or a common abbreviation like 'dnd' or 'pf2e'), add the official name to the `system` list.\n"
        "2. System Comparisons: If the user asks to compare mechanics across multiple games, include ALL relevant system names in the `system` list.\n"
        "3. Implicit Reference (Memory): If the current query lacks an explicit system, analyze the 'Recent History' and 'Previous Chat Summary'. If a game is clearly the active subject, map to that system.\n"
        "4. Anti-Hallucination (Strict Fallback): If NO system is mentioned and history does not establish one, YOU ARE STRICTLY FORBIDDEN FROM GUESSING. Set `system` to ['multiple'].\n"
        "5. Boundary Enforcement: DO NOT ANSWER THE USER'S QUESTION UNDER ANY CIRCUMSTANCES.\n\n"
        "TARGET SYSTEMS (Map all user abbreviations to these exact strings):\n"
        "{active_systems}\n\n"
        "PREVIOUS CHAT SUMMARY:\n"
        "{chat_summary}\n\n"
        "Output ONLY valid JSON matching the schema."
    )
    
    SYSTEMCA_USER_PROMPT: str = (
        "RECENT CHAT HISTORY:\n{recent_history}\n\n"
        "CURRENT USER QUESTION:\n{question}"
    )
    
    
    # KeyExpansion Prompt to return a list of new keywords
    KEYEXPANSION_SYSTEM_PROMPT: str = (
        "You are a highly specialized TTRPG Lexical & Semantic Keyword Expansion Engine.\n"
        "Your sole objective is to take a user's query and expand it into a list of precise, system-specific mechanical terms, rulebook concepts, action names, and search synonyms to maximize retrieval accuracy in a BM25 and Vector search engine.\n\n"
        "PRIORITY EVALUATION HIERARCHY (Strictly follow this order when generating terms):\n"
        "1. TARGET SYSTEM(S) & CURRENT USER QUERY (PRIMARY WEIGHT): Map casual or colloquial phrasing directly into the official rules terminology of the specified game system(s).\n"
        "2. CLEAN QUERY: Use the stripped, core intention of the user prompt to identify underlying game mechanics (e.g., actions, conditions, spells, checks).\n"
        "3. PREVIOUS KEYWORDS (IF PROVIDED): Analyze existing keywords to generate better synonyms, related mechanical subsystems, or alternative spellings/phrasings.\n"
        "4. RECENT CHAT HISTORY: Use recent context only to disambiguate pronouns or active combat state.\n"
        "5. CHAT SUMMARY (LOWEST WEIGHT): Use only as background context if the query relies on long-term campaign state.\n\n"
        "EXPANSION RULES:\n"
        "- System Domain Translation: Convert general descriptive actions into the exact official skill names, phase steps, or mechanical conditions defined by that specific game's ruleset.\n"
        "- Synonym & Concept Coverage: Include specific rules headers, condition names, die/check types, and alternative phrasing.\n"
        "- Strict Non-Conversational Output: DO NOT answer the question. Output ONLY valid JSON matching the schema.\n\n"
    )
    
    KEYEXPANSION_USER_PROMPT: str = (
        "CURRENT USER QUERY:\n"
        "{question}\n\n"    
        "TARGET SYSTEM(S):\n"
        "{selected_systems}\n\n"
        "CLEAN QUERY:\n"
        "{clean_query}\n\n"
        "PREVIOUS KEYWORDS (IF ANY):\n"
        "{previous_keywords}\n\n"
        "RECENT CHAT HISTORY:\n"
        "{recent_history}\n\n"
        "PREVIOUS CHAT SUMMARY:\n"
        "{chat_summary}\n\n"
    )
    
    
    # HyDE prompt to return a hallucinated answer that is jargon rich
    HYDE_SYSTEM_PROMPT: str = (
        "You are an expert Game Master and TTRPG Rules Architect.\n"
        "Your task is to generate a Hypothetical Document Embedding (HyDE) payload to maximize vector database retrieval.\n\n"
        "CONTEXTUAL WEIGHTING HIERARCHY:\n"
        "1. CURRENT USER QUERY (70% Weight): This is your primary focus. Address the specific mechanical question being asked.\n"
        "2. RECENT CHAT MESSAGES (20% Weight): Use this to disambiguate current combat states, active spells, or target subjects.\n"
        "3. CHAT SUMMARY (10% Weight): Use this strictly for deep background context or long-term campaign setting details.\n\n"
        "INTERNAL PROCESS (Execute silently):\n"
        "- Hallucinate a highly detailed, authoritative rulebook answer to the user's query.\n"
        "- Pack this hypothetical answer with dense, system-specific terminology, exact dice mechanics, conditions, and rulebook phrasing.\n\n"
        "OUTPUT GENERATION:\n"
        "1. Strip away all conversational prose, filler, and explanations from your hallucinated answer.\n"
        "2. Extract ONLY a list of the unique, high-value mechanical keywords and jargon.\n"
        "3. Identify the specific TTRPG game system(s) those mechanics definitively belong to.\n\n"
        "Output ONLY valid JSON matching the schema. Do NOT output the hallucinated text itself.\n\n"
    )
    
    HYDE_USER_PROMPT: str = (
        "CURRENT USER QUERY\n"
        "{question}\n\n"
        "RECENT CHAT MESSAGES\n"
        "{recent_history}\n\n"
        "CHAT SUMMARY\n"
        "{chat_summary}\n\n"
        
    )
    
 
@dataclass   
class Nodes:
    """
    Node Names stored globally for consistency
    """
    ROUTER: str = "router"
    RCRITIC: str = "routercritic"
    RFAIL: str = "routerfail"
    RETRIEVER: str = "retriever"
    SUMMARY: str = "summarizer"
    MEMORY: str = "memory"
    GAMEMASTER: str = "gamemaster"
    GMCRITIC: str = "gmcritic"
    GMFAIL: str = "gmfailsafe"
    SYSTEMCA: str = "systemca"
    KEYEXPD: str = "keyexpansion"
    HYDE: str = "hyde"